// Code generated by tools/clnrpcgen.py; DO NOT EDIT.

package clnrpc

import "context"

// GetInfo calls the getinfo Core Lightning RPC method.
func (c *Client) GetInfo(ctx context.Context) (*GetInfoResponse, error) {
	var result GetInfoResponse
	if err := c.Call(ctx, "getinfo", GetInfoRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListPeers calls the listpeers Core Lightning RPC method.
func (c *Client) ListPeers(ctx context.Context, req ListPeersRequest) (*ListPeersResponse, error) {
	var result ListPeersResponse
	if err := c.Call(ctx, "listpeers", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListFunds calls the listfunds Core Lightning RPC method.
func (c *Client) ListFunds(ctx context.Context, req ListFundsRequest) (*ListFundsResponse, error) {
	var result ListFundsResponse
	if err := c.Call(ctx, "listfunds", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendPay calls the sendpay Core Lightning RPC method.
func (c *Client) SendPay(ctx context.Context, req SendPayRequest) (*SendPayResponse, error) {
	var result SendPayResponse
	if err := c.Call(ctx, "sendpay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListChannels calls the listchannels Core Lightning RPC method.
func (c *Client) ListChannels(ctx context.Context, req ListChannelsRequest) (*ListChannelsResponse, error) {
	var result ListChannelsResponse
	if err := c.Call(ctx, "listchannels", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AddGossip calls the addgossip Core Lightning RPC method.
func (c *Client) AddGossip(ctx context.Context, req AddGossipRequest) (*AddGossipResponse, error) {
	var result AddGossipResponse
	if err := c.Call(ctx, "addgossip", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AddPSBTOutput calls the addpsbtoutput Core Lightning RPC method.
func (c *Client) AddPSBTOutput(ctx context.Context, req AddPSBTOutputRequest) (*AddPSBTOutputResponse, error) {
	var result AddPSBTOutputResponse
	if err := c.Call(ctx, "addpsbtoutput", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoCleanOnce calls the autoclean-once Core Lightning RPC method.
func (c *Client) AutoCleanOnce(ctx context.Context, req AutoCleanOnceRequest) (*AutoCleanOnceResponse, error) {
	var result AutoCleanOnceResponse
	if err := c.Call(ctx, "autoclean-once", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoCleanStatus calls the autoclean-status Core Lightning RPC method.
func (c *Client) AutoCleanStatus(ctx context.Context, req AutoCleanStatusRequest) (*AutoCleanStatusResponse, error) {
	var result AutoCleanStatusResponse
	if err := c.Call(ctx, "autoclean-status", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CheckMessage calls the checkmessage Core Lightning RPC method.
func (c *Client) CheckMessage(ctx context.Context, req CheckMessageRequest) (*CheckMessageResponse, error) {
	var result CheckMessageResponse
	if err := c.Call(ctx, "checkmessage", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Close calls the close Core Lightning RPC method.
func (c *Client) Close(ctx context.Context, req CloseRequest) (*CloseResponse, error) {
	var result CloseResponse
	if err := c.Call(ctx, "close", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Connect calls the connect Core Lightning RPC method.
func (c *Client) Connect(ctx context.Context, req ConnectRequest) (*ConnectResponse, error) {
	var result ConnectResponse
	if err := c.Call(ctx, "connect", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateInvoice calls the createinvoice Core Lightning RPC method.
func (c *Client) CreateInvoice(ctx context.Context, req CreateInvoiceRequest) (*CreateInvoiceResponse, error) {
	var result CreateInvoiceResponse
	if err := c.Call(ctx, "createinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Datastore calls the datastore Core Lightning RPC method.
func (c *Client) Datastore(ctx context.Context, req DatastoreRequest) (*DatastoreResponse, error) {
	var result DatastoreResponse
	if err := c.Call(ctx, "datastore", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DatastoreUsage calls the datastoreusage Core Lightning RPC method.
func (c *Client) DatastoreUsage(ctx context.Context, req DatastoreUsageRequest) (*DatastoreUsageResponse, error) {
	var result DatastoreUsageResponse
	if err := c.Call(ctx, "datastoreusage", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateOnion calls the createonion Core Lightning RPC method.
func (c *Client) CreateOnion(ctx context.Context, req CreateOnionRequest) (*CreateOnionResponse, error) {
	var result CreateOnionResponse
	if err := c.Call(ctx, "createonion", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelDatastore calls the deldatastore Core Lightning RPC method.
func (c *Client) DelDatastore(ctx context.Context, req DelDatastoreRequest) (*DelDatastoreResponse, error) {
	var result DelDatastoreResponse
	if err := c.Call(ctx, "deldatastore", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelInvoice calls the delinvoice Core Lightning RPC method.
func (c *Client) DelInvoice(ctx context.Context, req DelInvoiceRequest) (*DelInvoiceResponse, error) {
	var result DelInvoiceResponse
	if err := c.Call(ctx, "delinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DevForgetChannel calls the dev-forget-channel Core Lightning RPC method.
func (c *Client) DevForgetChannel(ctx context.Context, req DevForgetChannelRequest) (*DevForgetChannelResponse, error) {
	var result DevForgetChannelResponse
	if err := c.Call(ctx, "dev-forget-channel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EmergencyRecover calls the emergencyrecover Core Lightning RPC method.
func (c *Client) EmergencyRecover(ctx context.Context) (*EmergencyRecoverResponse, error) {
	var result EmergencyRecoverResponse
	if err := c.Call(ctx, "emergencyrecover", EmergencyRecoverRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetEmergencyRecoverData calls the getemergencyrecoverdata Core Lightning RPC method.
func (c *Client) GetEmergencyRecoverData(ctx context.Context) (*GetEmergencyRecoverDataResponse, error) {
	var result GetEmergencyRecoverDataResponse
	if err := c.Call(ctx, "getemergencyrecoverdata", GetEmergencyRecoverDataRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ExposeSecret calls the exposesecret Core Lightning RPC method.
func (c *Client) ExposeSecret(ctx context.Context, req ExposeSecretRequest) (*ExposeSecretResponse, error) {
	var result ExposeSecretResponse
	if err := c.Call(ctx, "exposesecret", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Recover calls the recover Core Lightning RPC method.
func (c *Client) Recover(ctx context.Context, req RecoverRequest) (*RecoverResponse, error) {
	var result RecoverResponse
	if err := c.Call(ctx, "recover", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// RecoverChannel calls the recoverchannel Core Lightning RPC method.
func (c *Client) RecoverChannel(ctx context.Context, req RecoverChannelRequest) (*RecoverChannelResponse, error) {
	var result RecoverChannelResponse
	if err := c.Call(ctx, "recoverchannel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Invoice calls the invoice Core Lightning RPC method.
func (c *Client) Invoice(ctx context.Context, req InvoiceRequest) (*InvoiceResponse, error) {
	var result InvoiceResponse
	if err := c.Call(ctx, "invoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceRequest calls the invoicerequest Core Lightning RPC method.
func (c *Client) InvoiceRequest(ctx context.Context, req InvoiceRequestRequest) (*InvoiceRequestResponse, error) {
	var result InvoiceRequestResponse
	if err := c.Call(ctx, "invoicerequest", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DisableInvoiceRequest calls the disableinvoicerequest Core Lightning RPC method.
func (c *Client) DisableInvoiceRequest(ctx context.Context, req DisableInvoiceRequestRequest) (*DisableInvoiceRequestResponse, error) {
	var result DisableInvoiceRequestResponse
	if err := c.Call(ctx, "disableinvoicerequest", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListInvoiceRequests calls the listinvoicerequests Core Lightning RPC method.
func (c *Client) ListInvoiceRequests(ctx context.Context, req ListInvoiceRequestsRequest) (*ListInvoiceRequestsResponse, error) {
	var result ListInvoiceRequestsResponse
	if err := c.Call(ctx, "listinvoicerequests", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListDatastore calls the listdatastore Core Lightning RPC method.
func (c *Client) ListDatastore(ctx context.Context, req ListDatastoreRequest) (*ListDatastoreResponse, error) {
	var result ListDatastoreResponse
	if err := c.Call(ctx, "listdatastore", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListInvoices calls the listinvoices Core Lightning RPC method.
func (c *Client) ListInvoices(ctx context.Context, req ListInvoicesRequest) (*ListInvoicesResponse, error) {
	var result ListInvoicesResponse
	if err := c.Call(ctx, "listinvoices", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendOnion calls the sendonion Core Lightning RPC method.
func (c *Client) SendOnion(ctx context.Context, req SendOnionRequest) (*SendOnionResponse, error) {
	var result SendOnionResponse
	if err := c.Call(ctx, "sendonion", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListSendPays calls the listsendpays Core Lightning RPC method.
func (c *Client) ListSendPays(ctx context.Context, req ListSendPaysRequest) (*ListSendPaysResponse, error) {
	var result ListSendPaysResponse
	if err := c.Call(ctx, "listsendpays", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListTransactions calls the listtransactions Core Lightning RPC method.
func (c *Client) ListTransactions(ctx context.Context) (*ListTransactionsResponse, error) {
	var result ListTransactionsResponse
	if err := c.Call(ctx, "listtransactions", ListTransactionsRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MakeSecret calls the makesecret Core Lightning RPC method.
func (c *Client) MakeSecret(ctx context.Context, req MakeSecretRequest) (*MakeSecretResponse, error) {
	var result MakeSecretResponse
	if err := c.Call(ctx, "makesecret", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Pay calls the pay Core Lightning RPC method.
func (c *Client) Pay(ctx context.Context, req PayRequest) (*PayResponse, error) {
	var result PayResponse
	if err := c.Call(ctx, "pay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListNodes calls the listnodes Core Lightning RPC method.
func (c *Client) ListNodes(ctx context.Context, req ListNodesRequest) (*ListNodesResponse, error) {
	var result ListNodesResponse
	if err := c.Call(ctx, "listnodes", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WaitAnyInvoice calls the waitanyinvoice Core Lightning RPC method.
func (c *Client) WaitAnyInvoice(ctx context.Context, req WaitAnyInvoiceRequest) (*WaitAnyInvoiceResponse, error) {
	var result WaitAnyInvoiceResponse
	if err := c.Call(ctx, "waitanyinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WaitInvoice calls the waitinvoice Core Lightning RPC method.
func (c *Client) WaitInvoice(ctx context.Context, req WaitInvoiceRequest) (*WaitInvoiceResponse, error) {
	var result WaitInvoiceResponse
	if err := c.Call(ctx, "waitinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WaitSendPay calls the waitsendpay Core Lightning RPC method.
func (c *Client) WaitSendPay(ctx context.Context, req WaitSendPayRequest) (*WaitSendPayResponse, error) {
	var result WaitSendPayResponse
	if err := c.Call(ctx, "waitsendpay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// NewAddr calls the newaddr Core Lightning RPC method.
func (c *Client) NewAddr(ctx context.Context, req NewAddrRequest) (*NewAddrResponse, error) {
	var result NewAddrResponse
	if err := c.Call(ctx, "newaddr", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Withdraw calls the withdraw Core Lightning RPC method.
func (c *Client) Withdraw(ctx context.Context, req WithdrawRequest) (*WithdrawResponse, error) {
	var result WithdrawResponse
	if err := c.Call(ctx, "withdraw", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// KeySend calls the keysend Core Lightning RPC method.
func (c *Client) KeySend(ctx context.Context, req KeySendRequest) (*KeySendResponse, error) {
	var result KeySendResponse
	if err := c.Call(ctx, "keysend", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FundPSBT calls the fundpsbt Core Lightning RPC method.
func (c *Client) FundPSBT(ctx context.Context, req FundPSBTRequest) (*FundPSBTResponse, error) {
	var result FundPSBTResponse
	if err := c.Call(ctx, "fundpsbt", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendPSBT calls the sendpsbt Core Lightning RPC method.
func (c *Client) SendPSBT(ctx context.Context, req SendPSBTRequest) (*SendPSBTResponse, error) {
	var result SendPSBTResponse
	if err := c.Call(ctx, "sendpsbt", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SignPSBT calls the signpsbt Core Lightning RPC method.
func (c *Client) SignPSBT(ctx context.Context, req SignPSBTRequest) (*SignPSBTResponse, error) {
	var result SignPSBTResponse
	if err := c.Call(ctx, "signpsbt", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UTXOPSBT calls the utxopsbt Core Lightning RPC method.
func (c *Client) UTXOPSBT(ctx context.Context, req UTXOPSBTRequest) (*UTXOPSBTResponse, error) {
	var result UTXOPSBTResponse
	if err := c.Call(ctx, "utxopsbt", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TXDiscard calls the txdiscard Core Lightning RPC method.
func (c *Client) TXDiscard(ctx context.Context, req TXDiscardRequest) (*TXDiscardResponse, error) {
	var result TXDiscardResponse
	if err := c.Call(ctx, "txdiscard", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TXPrepare calls the txprepare Core Lightning RPC method.
func (c *Client) TXPrepare(ctx context.Context, req TXPrepareRequest) (*TXPrepareResponse, error) {
	var result TXPrepareResponse
	if err := c.Call(ctx, "txprepare", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TXSend calls the txsend Core Lightning RPC method.
func (c *Client) TXSend(ctx context.Context, req TXSendRequest) (*TXSendResponse, error) {
	var result TXSendResponse
	if err := c.Call(ctx, "txsend", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListPeerChannels calls the listpeerchannels Core Lightning RPC method.
func (c *Client) ListPeerChannels(ctx context.Context, req ListPeerChannelsRequest) (*ListPeerChannelsResponse, error) {
	var result ListPeerChannelsResponse
	if err := c.Call(ctx, "listpeerchannels", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListClosedChannels calls the listclosedchannels Core Lightning RPC method.
func (c *Client) ListClosedChannels(ctx context.Context, req ListClosedChannelsRequest) (*ListClosedChannelsResponse, error) {
	var result ListClosedChannelsResponse
	if err := c.Call(ctx, "listclosedchannels", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Decode calls the decode Core Lightning RPC method.
func (c *Client) Decode(ctx context.Context, req DecodeRequest) (*DecodeResponse, error) {
	var result DecodeResponse
	if err := c.Call(ctx, "decode", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelPay calls the delpay Core Lightning RPC method.
func (c *Client) DelPay(ctx context.Context, req DelPayRequest) (*DelPayResponse, error) {
	var result DelPayResponse
	if err := c.Call(ctx, "delpay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelForward calls the delforward Core Lightning RPC method.
func (c *Client) DelForward(ctx context.Context, req DelForwardRequest) (*DelForwardResponse, error) {
	var result DelForwardResponse
	if err := c.Call(ctx, "delforward", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DisableOffer calls the disableoffer Core Lightning RPC method.
func (c *Client) DisableOffer(ctx context.Context, req DisableOfferRequest) (*DisableOfferResponse, error) {
	var result DisableOfferResponse
	if err := c.Call(ctx, "disableoffer", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EnableOffer calls the enableoffer Core Lightning RPC method.
func (c *Client) EnableOffer(ctx context.Context, req EnableOfferRequest) (*EnableOfferResponse, error) {
	var result EnableOfferResponse
	if err := c.Call(ctx, "enableoffer", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Disconnect calls the disconnect Core Lightning RPC method.
func (c *Client) Disconnect(ctx context.Context, req DisconnectRequest) (*DisconnectResponse, error) {
	var result DisconnectResponse
	if err := c.Call(ctx, "disconnect", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Feerates calls the feerates Core Lightning RPC method.
func (c *Client) Feerates(ctx context.Context, req FeeratesRequest) (*FeeratesResponse, error) {
	var result FeeratesResponse
	if err := c.Call(ctx, "feerates", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FetchBip353 calls the fetchbip353 Core Lightning RPC method.
func (c *Client) FetchBip353(ctx context.Context, req FetchBip353Request) (*FetchBip353Response, error) {
	var result FetchBip353Response
	if err := c.Call(ctx, "fetchbip353", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FetchInvoice calls the fetchinvoice Core Lightning RPC method.
func (c *Client) FetchInvoice(ctx context.Context, req FetchInvoiceRequest) (*FetchInvoiceResponse, error) {
	var result FetchInvoiceResponse
	if err := c.Call(ctx, "fetchinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelRecurringInvoice calls the cancelrecurringinvoice Core Lightning RPC method.
func (c *Client) CancelRecurringInvoice(ctx context.Context, req CancelRecurringInvoiceRequest) (*CancelRecurringInvoiceResponse, error) {
	var result CancelRecurringInvoiceResponse
	if err := c.Call(ctx, "cancelrecurringinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FundChannelCancel calls the fundchannel_cancel Core Lightning RPC method.
func (c *Client) FundChannelCancel(ctx context.Context, req FundChannelCancelRequest) (*FundChannelCancelResponse, error) {
	var result FundChannelCancelResponse
	if err := c.Call(ctx, "fundchannel_cancel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FundChannelComplete calls the fundchannel_complete Core Lightning RPC method.
func (c *Client) FundChannelComplete(ctx context.Context, req FundChannelCompleteRequest) (*FundChannelCompleteResponse, error) {
	var result FundChannelCompleteResponse
	if err := c.Call(ctx, "fundchannel_complete", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FundChannel calls the fundchannel Core Lightning RPC method.
func (c *Client) FundChannel(ctx context.Context, req FundChannelRequest) (*FundChannelResponse, error) {
	var result FundChannelResponse
	if err := c.Call(ctx, "fundchannel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FundChannelStart calls the fundchannel_start Core Lightning RPC method.
func (c *Client) FundChannelStart(ctx context.Context, req FundChannelStartRequest) (*FundChannelStartResponse, error) {
	var result FundChannelStartResponse
	if err := c.Call(ctx, "fundchannel_start", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetLog calls the getlog Core Lightning RPC method.
func (c *Client) GetLog(ctx context.Context, req GetLogRequest) (*GetLogResponse, error) {
	var result GetLogResponse
	if err := c.Call(ctx, "getlog", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FunderUpdate calls the funderupdate Core Lightning RPC method.
func (c *Client) FunderUpdate(ctx context.Context, req FunderUpdateRequest) (*FunderUpdateResponse, error) {
	var result FunderUpdateResponse
	if err := c.Call(ctx, "funderupdate", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetRoute calls the getroute Core Lightning RPC method.
func (c *Client) GetRoute(ctx context.Context, req GetRouteRequest) (*GetRouteResponse, error) {
	var result GetRouteResponse
	if err := c.Call(ctx, "getroute", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListAddresses calls the listaddresses Core Lightning RPC method.
func (c *Client) ListAddresses(ctx context.Context, req ListAddressesRequest) (*ListAddressesResponse, error) {
	var result ListAddressesResponse
	if err := c.Call(ctx, "listaddresses", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListForwards calls the listforwards Core Lightning RPC method.
func (c *Client) ListForwards(ctx context.Context, req ListForwardsRequest) (*ListForwardsResponse, error) {
	var result ListForwardsResponse
	if err := c.Call(ctx, "listforwards", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListOffers calls the listoffers Core Lightning RPC method.
func (c *Client) ListOffers(ctx context.Context, req ListOffersRequest) (*ListOffersResponse, error) {
	var result ListOffersResponse
	if err := c.Call(ctx, "listoffers", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListPays calls the listpays Core Lightning RPC method.
func (c *Client) ListPays(ctx context.Context, req ListPaysRequest) (*ListPaysResponse, error) {
	var result ListPaysResponse
	if err := c.Call(ctx, "listpays", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListHtlcs calls the listhtlcs Core Lightning RPC method.
func (c *Client) ListHtlcs(ctx context.Context, req ListHtlcsRequest) (*ListHtlcsResponse, error) {
	var result ListHtlcsResponse
	if err := c.Call(ctx, "listhtlcs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MultiFundChannel calls the multifundchannel Core Lightning RPC method.
func (c *Client) MultiFundChannel(ctx context.Context, req MultiFundChannelRequest) (*MultiFundChannelResponse, error) {
	var result MultiFundChannelResponse
	if err := c.Call(ctx, "multifundchannel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MultiWithdraw calls the multiwithdraw Core Lightning RPC method.
func (c *Client) MultiWithdraw(ctx context.Context, req MultiWithdrawRequest) (*MultiWithdrawResponse, error) {
	var result MultiWithdrawResponse
	if err := c.Call(ctx, "multiwithdraw", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Offer calls the offer Core Lightning RPC method.
func (c *Client) Offer(ctx context.Context, req OfferRequest) (*OfferResponse, error) {
	var result OfferResponse
	if err := c.Call(ctx, "offer", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OpenChannelAbort calls the openchannel_abort Core Lightning RPC method.
func (c *Client) OpenChannelAbort(ctx context.Context, req OpenChannelAbortRequest) (*OpenChannelAbortResponse, error) {
	var result OpenChannelAbortResponse
	if err := c.Call(ctx, "openchannel_abort", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OpenChannelBump calls the openchannel_bump Core Lightning RPC method.
func (c *Client) OpenChannelBump(ctx context.Context, req OpenChannelBumpRequest) (*OpenChannelBumpResponse, error) {
	var result OpenChannelBumpResponse
	if err := c.Call(ctx, "openchannel_bump", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OpenChannelInit calls the openchannel_init Core Lightning RPC method.
func (c *Client) OpenChannelInit(ctx context.Context, req OpenChannelInitRequest) (*OpenChannelInitResponse, error) {
	var result OpenChannelInitResponse
	if err := c.Call(ctx, "openchannel_init", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OpenChannelSigned calls the openchannel_signed Core Lightning RPC method.
func (c *Client) OpenChannelSigned(ctx context.Context, req OpenChannelSignedRequest) (*OpenChannelSignedResponse, error) {
	var result OpenChannelSignedResponse
	if err := c.Call(ctx, "openchannel_signed", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OpenChannelUpdate calls the openchannel_update Core Lightning RPC method.
func (c *Client) OpenChannelUpdate(ctx context.Context, req OpenChannelUpdateRequest) (*OpenChannelUpdateResponse, error) {
	var result OpenChannelUpdateResponse
	if err := c.Call(ctx, "openchannel_update", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ping calls the ping Core Lightning RPC method.
func (c *Client) Ping(ctx context.Context, req PingRequest) (*PingResponse, error) {
	var result PingResponse
	if err := c.Call(ctx, "ping", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Plugin calls the plugin Core Lightning RPC method.
func (c *Client) Plugin(ctx context.Context, req PluginRequest) (*PluginResponse, error) {
	var result PluginResponse
	if err := c.Call(ctx, "plugin", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// RenePayStatus calls the renepaystatus Core Lightning RPC method.
func (c *Client) RenePayStatus(ctx context.Context, req RenePayStatusRequest) (*RenePayStatusResponse, error) {
	var result RenePayStatusResponse
	if err := c.Call(ctx, "renepaystatus", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// RenePay calls the renepay Core Lightning RPC method.
func (c *Client) RenePay(ctx context.Context, req RenePayRequest) (*RenePayResponse, error) {
	var result RenePayResponse
	if err := c.Call(ctx, "renepay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReserveInputs calls the reserveinputs Core Lightning RPC method.
func (c *Client) ReserveInputs(ctx context.Context, req ReserveInputsRequest) (*ReserveInputsResponse, error) {
	var result ReserveInputsResponse
	if err := c.Call(ctx, "reserveinputs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendCustomMsg calls the sendcustommsg Core Lightning RPC method.
func (c *Client) SendCustomMsg(ctx context.Context, req SendCustomMsgRequest) (*SendCustomMsgResponse, error) {
	var result SendCustomMsgResponse
	if err := c.Call(ctx, "sendcustommsg", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendInvoice calls the sendinvoice Core Lightning RPC method.
func (c *Client) SendInvoice(ctx context.Context, req SendInvoiceRequest) (*SendInvoiceResponse, error) {
	var result SendInvoiceResponse
	if err := c.Call(ctx, "sendinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SetChannel calls the setchannel Core Lightning RPC method.
func (c *Client) SetChannel(ctx context.Context, req SetChannelRequest) (*SetChannelResponse, error) {
	var result SetChannelResponse
	if err := c.Call(ctx, "setchannel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SetConfig calls the setconfig Core Lightning RPC method.
func (c *Client) SetConfig(ctx context.Context, req SetConfigRequest) (*SetConfigResponse, error) {
	var result SetConfigResponse
	if err := c.Call(ctx, "setconfig", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SetPSBTVersion calls the setpsbtversion Core Lightning RPC method.
func (c *Client) SetPSBTVersion(ctx context.Context, req SetPSBTVersionRequest) (*SetPSBTVersionResponse, error) {
	var result SetPSBTVersionResponse
	if err := c.Call(ctx, "setpsbtversion", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SignInvoice calls the signinvoice Core Lightning RPC method.
func (c *Client) SignInvoice(ctx context.Context, req SignInvoiceRequest) (*SignInvoiceResponse, error) {
	var result SignInvoiceResponse
	if err := c.Call(ctx, "signinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SignMessage calls the signmessage Core Lightning RPC method.
func (c *Client) SignMessage(ctx context.Context, req SignMessageRequest) (*SignMessageResponse, error) {
	var result SignMessageResponse
	if err := c.Call(ctx, "signmessage", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpliceInit calls the splice_init Core Lightning RPC method.
func (c *Client) SpliceInit(ctx context.Context, req SpliceInitRequest) (*SpliceInitResponse, error) {
	var result SpliceInitResponse
	if err := c.Call(ctx, "splice_init", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpliceSigned calls the splice_signed Core Lightning RPC method.
func (c *Client) SpliceSigned(ctx context.Context, req SpliceSignedRequest) (*SpliceSignedResponse, error) {
	var result SpliceSignedResponse
	if err := c.Call(ctx, "splice_signed", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpliceUpdate calls the splice_update Core Lightning RPC method.
func (c *Client) SpliceUpdate(ctx context.Context, req SpliceUpdateRequest) (*SpliceUpdateResponse, error) {
	var result SpliceUpdateResponse
	if err := c.Call(ctx, "splice_update", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpliceIn calls the splicein Core Lightning RPC method.
func (c *Client) SpliceIn(ctx context.Context, req SpliceInRequest) (*SpliceInResponse, error) {
	var result SpliceInResponse
	if err := c.Call(ctx, "splicein", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpliceOut calls the spliceout Core Lightning RPC method.
func (c *Client) SpliceOut(ctx context.Context, req SpliceOutRequest) (*SpliceOutResponse, error) {
	var result SpliceOutResponse
	if err := c.Call(ctx, "spliceout", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DevSplice calls the dev-splice Core Lightning RPC method.
func (c *Client) DevSplice(ctx context.Context, req DevSpliceRequest) (*DevSpliceResponse, error) {
	var result DevSpliceResponse
	if err := c.Call(ctx, "dev-splice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UnreserveInputs calls the unreserveinputs Core Lightning RPC method.
func (c *Client) UnreserveInputs(ctx context.Context, req UnreserveInputsRequest) (*UnreserveInputsResponse, error) {
	var result UnreserveInputsResponse
	if err := c.Call(ctx, "unreserveinputs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpgradeWallet calls the upgradewallet Core Lightning RPC method.
func (c *Client) UpgradeWallet(ctx context.Context, req UpgradeWalletRequest) (*UpgradeWalletResponse, error) {
	var result UpgradeWalletResponse
	if err := c.Call(ctx, "upgradewallet", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WaitBlockHeight calls the waitblockheight Core Lightning RPC method.
func (c *Client) WaitBlockHeight(ctx context.Context, req WaitBlockHeightRequest) (*WaitBlockHeightResponse, error) {
	var result WaitBlockHeightResponse
	if err := c.Call(ctx, "waitblockheight", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Wait calls the wait Core Lightning RPC method.
func (c *Client) Wait(ctx context.Context, req WaitRequest) (*WaitResponse, error) {
	var result WaitResponse
	if err := c.Call(ctx, "wait", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListConfigs calls the listconfigs Core Lightning RPC method.
func (c *Client) ListConfigs(ctx context.Context, req ListConfigsRequest) (*ListConfigsResponse, error) {
	var result ListConfigsResponse
	if err := c.Call(ctx, "listconfigs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stop calls the stop Core Lightning RPC method.
func (c *Client) Stop(ctx context.Context) (*StopResponse, error) {
	var result StopResponse
	if err := c.Call(ctx, "stop", StopRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Help calls the help Core Lightning RPC method.
func (c *Client) Help(ctx context.Context, req HelpRequest) (*HelpResponse, error) {
	var result HelpResponse
	if err := c.Call(ctx, "help", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PreApproveKeysend calls the preapprovekeysend Core Lightning RPC method.
func (c *Client) PreApproveKeysend(ctx context.Context, req PreApproveKeysendRequest) (*PreApproveKeysendResponse, error) {
	var result PreApproveKeysendResponse
	if err := c.Call(ctx, "preapprovekeysend", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PreApproveInvoice calls the preapproveinvoice Core Lightning RPC method.
func (c *Client) PreApproveInvoice(ctx context.Context, req PreApproveInvoiceRequest) (*PreApproveInvoiceResponse, error) {
	var result PreApproveInvoiceResponse
	if err := c.Call(ctx, "preapproveinvoice", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// StaticBackup calls the staticbackup Core Lightning RPC method.
func (c *Client) StaticBackup(ctx context.Context) (*StaticBackupResponse, error) {
	var result StaticBackupResponse
	if err := c.Call(ctx, "staticbackup", StaticBackupRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprChannelsApy calls the bkpr-channelsapy Core Lightning RPC method.
func (c *Client) BkprChannelsApy(ctx context.Context, req BkprChannelsApyRequest) (*BkprChannelsApyResponse, error) {
	var result BkprChannelsApyResponse
	if err := c.Call(ctx, "bkpr-channelsapy", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprDumpIncomeCSV calls the bkpr-dumpincomecsv Core Lightning RPC method.
func (c *Client) BkprDumpIncomeCSV(ctx context.Context, req BkprDumpIncomeCSVRequest) (*BkprDumpIncomeCSVResponse, error) {
	var result BkprDumpIncomeCSVResponse
	if err := c.Call(ctx, "bkpr-dumpincomecsv", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprInspect calls the bkpr-inspect Core Lightning RPC method.
func (c *Client) BkprInspect(ctx context.Context, req BkprInspectRequest) (*BkprInspectResponse, error) {
	var result BkprInspectResponse
	if err := c.Call(ctx, "bkpr-inspect", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprListAccountEvents calls the bkpr-listaccountevents Core Lightning RPC method.
func (c *Client) BkprListAccountEvents(ctx context.Context, req BkprListAccountEventsRequest) (*BkprListAccountEventsResponse, error) {
	var result BkprListAccountEventsResponse
	if err := c.Call(ctx, "bkpr-listaccountevents", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprListBalances calls the bkpr-listbalances Core Lightning RPC method.
func (c *Client) BkprListBalances(ctx context.Context) (*BkprListBalancesResponse, error) {
	var result BkprListBalancesResponse
	if err := c.Call(ctx, "bkpr-listbalances", BkprListBalancesRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprListIncome calls the bkpr-listincome Core Lightning RPC method.
func (c *Client) BkprListIncome(ctx context.Context, req BkprListIncomeRequest) (*BkprListIncomeResponse, error) {
	var result BkprListIncomeResponse
	if err := c.Call(ctx, "bkpr-listincome", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprEditDescriptionByPaymentID calls the bkpr-editdescriptionbypaymentid Core Lightning RPC method.
func (c *Client) BkprEditDescriptionByPaymentID(ctx context.Context, req BkprEditDescriptionByPaymentIDRequest) (*BkprEditDescriptionByPaymentIDResponse, error) {
	var result BkprEditDescriptionByPaymentIDResponse
	if err := c.Call(ctx, "bkpr-editdescriptionbypaymentid", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprEditDescriptionByOutpoint calls the bkpr-editdescriptionbyoutpoint Core Lightning RPC method.
func (c *Client) BkprEditDescriptionByOutpoint(ctx context.Context, req BkprEditDescriptionByOutpointRequest) (*BkprEditDescriptionByOutpointResponse, error) {
	var result BkprEditDescriptionByOutpointResponse
	if err := c.Call(ctx, "bkpr-editdescriptionbyoutpoint", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BkprReport calls the bkpr-report Core Lightning RPC method.
func (c *Client) BkprReport(ctx context.Context, req BkprReportRequest) (*BkprReportResponse, error) {
	var result BkprReportResponse
	if err := c.Call(ctx, "bkpr-report", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BlacklistRune calls the blacklistrune Core Lightning RPC method.
func (c *Client) BlacklistRune(ctx context.Context, req BlacklistRuneRequest) (*BlacklistRuneResponse, error) {
	var result BlacklistRuneResponse
	if err := c.Call(ctx, "blacklistrune", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CheckRune calls the checkrune Core Lightning RPC method.
func (c *Client) CheckRune(ctx context.Context, req CheckRuneRequest) (*CheckRuneResponse, error) {
	var result CheckRuneResponse
	if err := c.Call(ctx, "checkrune", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateRune calls the createrune Core Lightning RPC method.
func (c *Client) CreateRune(ctx context.Context, req CreateRuneRequest) (*CreateRuneResponse, error) {
	var result CreateRuneResponse
	if err := c.Call(ctx, "createrune", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ShowRunes calls the showrunes Core Lightning RPC method.
func (c *Client) ShowRunes(ctx context.Context, req ShowRunesRequest) (*ShowRunesResponse, error) {
	var result ShowRunesResponse
	if err := c.Call(ctx, "showrunes", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneUnreserve calls the askrene-unreserve Core Lightning RPC method.
func (c *Client) AskReneUnreserve(ctx context.Context, req AskReneUnreserveRequest) (*AskReneUnreserveResponse, error) {
	var result AskReneUnreserveResponse
	if err := c.Call(ctx, "askrene-unreserve", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneListLayers calls the askrene-listlayers Core Lightning RPC method.
func (c *Client) AskReneListLayers(ctx context.Context, req AskReneListLayersRequest) (*AskReneListLayersResponse, error) {
	var result AskReneListLayersResponse
	if err := c.Call(ctx, "askrene-listlayers", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneCreateLayer calls the askrene-create-layer Core Lightning RPC method.
func (c *Client) AskReneCreateLayer(ctx context.Context, req AskReneCreateLayerRequest) (*AskReneCreateLayerResponse, error) {
	var result AskReneCreateLayerResponse
	if err := c.Call(ctx, "askrene-create-layer", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneRemoveLayer calls the askrene-remove-layer Core Lightning RPC method.
func (c *Client) AskReneRemoveLayer(ctx context.Context, req AskReneRemoveLayerRequest) (*AskReneRemoveLayerResponse, error) {
	var result AskReneRemoveLayerResponse
	if err := c.Call(ctx, "askrene-remove-layer", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneRemoveChannelUpdate calls the askrene-remove-channel-update Core Lightning RPC method.
func (c *Client) AskReneRemoveChannelUpdate(ctx context.Context, req AskReneRemoveChannelUpdateRequest) (*AskReneRemoveChannelUpdateResponse, error) {
	var result AskReneRemoveChannelUpdateResponse
	if err := c.Call(ctx, "askrene-remove-channel-update", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneReserve calls the askrene-reserve Core Lightning RPC method.
func (c *Client) AskReneReserve(ctx context.Context, req AskReneReserveRequest) (*AskReneReserveResponse, error) {
	var result AskReneReserveResponse
	if err := c.Call(ctx, "askrene-reserve", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneAge calls the askrene-age Core Lightning RPC method.
func (c *Client) AskReneAge(ctx context.Context, req AskReneAgeRequest) (*AskReneAgeResponse, error) {
	var result AskReneAgeResponse
	if err := c.Call(ctx, "askrene-age", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetRoutes calls the getroutes Core Lightning RPC method.
func (c *Client) GetRoutes(ctx context.Context, req GetRoutesRequest) (*GetRoutesResponse, error) {
	var result GetRoutesResponse
	if err := c.Call(ctx, "getroutes", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneDisableNode calls the askrene-disable-node Core Lightning RPC method.
func (c *Client) AskReneDisableNode(ctx context.Context, req AskReneDisableNodeRequest) (*AskReneDisableNodeResponse, error) {
	var result AskReneDisableNodeResponse
	if err := c.Call(ctx, "askrene-disable-node", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneInformChannel calls the askrene-inform-channel Core Lightning RPC method.
func (c *Client) AskReneInformChannel(ctx context.Context, req AskReneInformChannelRequest) (*AskReneInformChannelResponse, error) {
	var result AskReneInformChannelResponse
	if err := c.Call(ctx, "askrene-inform-channel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneCreateChannel calls the askrene-create-channel Core Lightning RPC method.
func (c *Client) AskReneCreateChannel(ctx context.Context, req AskReneCreateChannelRequest) (*AskReneCreateChannelResponse, error) {
	var result AskReneCreateChannelResponse
	if err := c.Call(ctx, "askrene-create-channel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneUpdateChannel calls the askrene-update-channel Core Lightning RPC method.
func (c *Client) AskReneUpdateChannel(ctx context.Context, req AskReneUpdateChannelRequest) (*AskReneUpdateChannelResponse, error) {
	var result AskReneUpdateChannelResponse
	if err := c.Call(ctx, "askrene-update-channel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneBiasChannel calls the askrene-bias-channel Core Lightning RPC method.
func (c *Client) AskReneBiasChannel(ctx context.Context, req AskReneBiasChannelRequest) (*AskReneBiasChannelResponse, error) {
	var result AskReneBiasChannelResponse
	if err := c.Call(ctx, "askrene-bias-channel", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskreneBiasNode calls the askrene-bias-node Core Lightning RPC method.
func (c *Client) AskreneBiasNode(ctx context.Context, req AskreneBiasNodeRequest) (*AskreneBiasNodeResponse, error) {
	var result AskreneBiasNodeResponse
	if err := c.Call(ctx, "askrene-bias-node", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AskReneListReservations calls the askrene-listreservations Core Lightning RPC method.
func (c *Client) AskReneListReservations(ctx context.Context) (*AskReneListReservationsResponse, error) {
	var result AskReneListReservationsResponse
	if err := c.Call(ctx, "askrene-listreservations", AskReneListReservationsRequest{}, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InjectPaymentOnion calls the injectpaymentonion Core Lightning RPC method.
func (c *Client) InjectPaymentOnion(ctx context.Context, req InjectPaymentOnionRequest) (*InjectPaymentOnionResponse, error) {
	var result InjectPaymentOnionResponse
	if err := c.Call(ctx, "injectpaymentonion", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InjectOnionMessage calls the injectonionmessage Core Lightning RPC method.
func (c *Client) InjectOnionMessage(ctx context.Context, req InjectOnionMessageRequest) (*InjectOnionMessageResponse, error) {
	var result InjectOnionMessageResponse
	if err := c.Call(ctx, "injectonionmessage", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Xpay calls the xpay Core Lightning RPC method.
func (c *Client) Xpay(ctx context.Context, req XpayRequest) (*XpayResponse, error) {
	var result XpayResponse
	if err := c.Call(ctx, "xpay", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SignMessageWithKey calls the signmessagewithkey Core Lightning RPC method.
func (c *Client) SignMessageWithKey(ctx context.Context, req SignMessageWithKeyRequest) (*SignMessageWithKeyResponse, error) {
	var result SignMessageWithKeyResponse
	if err := c.Call(ctx, "signmessagewithkey", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListChannelMoves calls the listchannelmoves Core Lightning RPC method.
func (c *Client) ListChannelMoves(ctx context.Context, req ListChannelMovesRequest) (*ListChannelMovesResponse, error) {
	var result ListChannelMovesResponse
	if err := c.Call(ctx, "listchannelmoves", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListChainMoves calls the listchainmoves Core Lightning RPC method.
func (c *Client) ListChainMoves(ctx context.Context, req ListChainMovesRequest) (*ListChainMovesResponse, error) {
	var result ListChainMovesResponse
	if err := c.Call(ctx, "listchainmoves", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListNetworkEvents calls the listnetworkevents Core Lightning RPC method.
func (c *Client) ListNetworkEvents(ctx context.Context, req ListNetworkEventsRequest) (*ListNetworkEventsResponse, error) {
	var result ListNetworkEventsResponse
	if err := c.Call(ctx, "listnetworkevents", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelNetworkEvent calls the delnetworkevent Core Lightning RPC method.
func (c *Client) DelNetworkEvent(ctx context.Context, req DelNetworkEventRequest) (*DelNetworkEventResponse, error) {
	var result DelNetworkEventResponse
	if err := c.Call(ctx, "delnetworkevent", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ClnrestRegisterPath calls the clnrest-register-path Core Lightning RPC method.
func (c *Client) ClnrestRegisterPath(ctx context.Context, req ClnrestRegisterPathRequest) (*ClnrestRegisterPathResponse, error) {
	var result ClnrestRegisterPathResponse
	if err := c.Call(ctx, "clnrest-register-path", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListCurrencyRates calls the listcurrencyrates Core Lightning RPC method.
func (c *Client) ListCurrencyRates(ctx context.Context, req ListCurrencyRatesRequest) (*ListCurrencyRatesResponse, error) {
	var result ListCurrencyRatesResponse
	if err := c.Call(ctx, "listcurrencyrates", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CurrencyConvert calls the currencyconvert Core Lightning RPC method.
func (c *Client) CurrencyConvert(ctx context.Context, req CurrencyConvertRequest) (*CurrencyConvertResponse, error) {
	var result CurrencyConvertResponse
	if err := c.Call(ctx, "currencyconvert", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CurrencyRate calls the currencyrate Core Lightning RPC method.
func (c *Client) CurrencyRate(ctx context.Context, req CurrencyRateRequest) (*CurrencyRateResponse, error) {
	var result CurrencyRateResponse
	if err := c.Call(ctx, "currencyrate", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SendAmount calls the sendamount Core Lightning RPC method.
func (c *Client) SendAmount(ctx context.Context, req SendAmountRequest) (*SendAmountResponse, error) {
	var result SendAmountResponse
	if err := c.Call(ctx, "sendamount", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateProof calls the createproof Core Lightning RPC method.
func (c *Client) CreateProof(ctx context.Context, req CreateProofRequest) (*CreateProofResponse, error) {
	var result CreateProofResponse
	if err := c.Call(ctx, "createproof", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Xkeysend calls the xkeysend Core Lightning RPC method.
func (c *Client) Xkeysend(ctx context.Context, req XkeysendRequest) (*XkeysendResponse, error) {
	var result XkeysendResponse
	if err := c.Call(ctx, "xkeysend", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Graceful calls the graceful Core Lightning RPC method.
func (c *Client) Graceful(ctx context.Context, req GracefulRequest) (*GracefulResponse, error) {
	var result GracefulResponse
	if err := c.Call(ctx, "graceful", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
